In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

In [21]:
spam_data= pd.read_csv("spam.csv" , encoding= "latin-1")

In [22]:
spam_data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [23]:
print(type(spam_data))

<class 'pandas.core.frame.DataFrame'>

In [24]:
spam_data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [25]:
spam_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
x = spam_data["v2"]
x = np.array(x)

In [55]:
x

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [56]:
y = spam_data["v1"]
y = np.array(y)

In [57]:
y

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype=object)

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [69]:
model = GaussianNB()

In [70]:
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [71]:
x_train

<4457x7705 sparse matrix of type '<class 'numpy.float64'>'
	with 58975 stored elements in Compressed Sparse Row format>

In [74]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [75]:
model.fit(x_train, y_train)

GaussianNB()

In [76]:
y_predicted = model.predict(x_test)

In [77]:
y_predicted

array(['spam', 'ham', 'spam', ..., 'ham', 'spam', 'ham'], dtype='<U4')

In [78]:
y_test

array(['spam', 'ham', 'ham', ..., 'ham', 'spam', 'ham'], dtype=object)

In [81]:
from sklearn.metrics import accuracy_score

In [82]:
print(accuracy_score(y_test, y_predicted))

0.9004484304932735

In [85]:
from sklearn.metrics import classification_report

In [86]:
from sklearn import metrics
matrix = metrics.confusion_matrix(y_test, y_predicted)

In [87]:
matrix

array([[883,  94],
       [ 17, 121]], dtype=int64)

In [88]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

         ham       0.98      0.90      0.94       977
        spam       0.56      0.88      0.69       138

    accuracy                           0.90      1115
   macro avg       0.77      0.89      0.81      1115
weighted avg       0.93      0.90      0.91      1115